### ISSUE TITLE
Cannot import ATVPlayer to a Swift 5 project.

### ISSUE THREAD

**Issue by RomanPodymov** [zensis-ltd/atvplayer-tvos#1]
Hello.
I tried to import `ATVPlayer` to my Swift 5 project, but got the following error: `Module compiled with Swift 4.2 cannot be imported by the Swift 5.0 compiler`.
Could you please provide a version of `ATVPlayer` compatible with Swift 5?

**Comment by cmhvin** [comment]
Hello, 
Please try to use latest version (2.0.2). The problem should be solved.
Thanks.
