### ISSUE TITLE
Could not find module 'ATVPlayer' for architecture 'x86_64'; found: arm64

### ISSUE THREAD

**Issue by mhabashy** [zensis-ltd/atvplayer-tvos#3]
Hello Developers,

I am having an issue with error on the architecture.
 
`Could not find module 'ATVPlayer' for architecture 'x86_64'; found: arm64` 

Even on the demo project that was on your github, it is returning me this error. On two different Mac Pros. 

If you could please help that will be great. 

thanks,

Michael

**Comment by vincent0225** [comment]
Please try to use ATVPlayer latest version.
Thanks.

**Comment by cmhvin** [comment]
Please try to use ATVPlayer latest version
