### ISSUE TITLE
DRM support

### ISSUE THREAD

**Issue by RomanPodymov** [zensis-ltd/atvplayer-tvos#4]
Hello.
As I can see currently there is no way how to play streams with DRM. Are you going to add this feature to **ATVPlayer**?

**Comment by cmhvin** [comment]
Hello, we are checking it

**Comment by cmhvin** [comment]
@RomanPodymov 
Do you have DRM testing stream for us to test?
Thanks.

**Comment by RomanPodymov** [comment]
Hello @cmhvin 
I will try to find a stream for testing. BTW I guess you should add to your player something that was already described in this [gist](https://gist.github.com/fousa/5709fb7c84e5b53dbdae508c9cb4fadc).

**Comment by RomanPodymov** [comment]
Hello @cmhvin 
I've sent a mail to service@zensis.com with the code that explains what we need. Don't hesitate to ask me any question regarding the code.

**Comment by cmhvin** [comment]
@RomanPodymov 
Could you help to try our new version by
```
pod 'ATVPlayer' , :git => 'https://github.com/zensis-ltd/ATVPlayer-cocoapod.git', :branch => 'AVURLAsset'
```

It allowed developer to pass their own AVUrlAsset to ATVPlayer
```
let asset = AVURLAsset(url: <URL>)
let queue = DispatchQueue(label: "FP License Acquire")
asset.resourceLoader.setDelegate(self, queue: queue)
player.play(with:<ATVMediaItem>, avurlAsset: asset, startPosition: 0)
```

You can implement the delegate method in your vc.

**Comment by RomanPodymov** [comment]
Hello @cmhvin,
Thanks, I guess this is exactly what we need. We will check this feature and report if it works as expected.

**Comment by RomanPodymov** [comment]
Hello @cmhvin 
DRM support implemented in https://github.com/zensis-ltd/ATVPlayer-cocoapod.git works fine. Please release a new **ATVPlayer** version with these changes.

**Comment by cmhvin** [comment]
@RomanPodymov 
Thanks. We will prepare it.
